apiVersion: v1
kind: Pod
metadata:
spec:
#  securityContext:
#    runAsUser: 1000 # default UID of jenkins user in default jnlp image
  containers:
  - name: jnlp
    image: registry.redhat.io/openshift3/jenkins-agent-maven-35-rhel7:v3.11
    imagePullPolicy: "Always"
    resources:
      limits: {}
      requests: {}
    securityContext:
      privileged: false
    tty: false
    volumeMounts:
    - mountPath: "/tmp"
      name: "workspace-volume"
      readOnly: false
    workingDir: "/tmp"
  hostNetwork: false
  restartPolicy: "Never"
  volumes:
  - emptyDir:
      medium: ""
    name: "workspace-volume"
